apiVersion: apps/v1
kind: Deployment
metadata:
  name: me
spec:
  selector:
    matchLabels:
      run: me
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: me
    spec:
      containers:
      - name: me
        image: jeg910716/me
        ports:
        - containerPort: 80
---	
apiVersion: v1	
kind: Service	
metadata:	
  name: me-dev	
  labels:	
    run: me
spec:	
  selector:	
    run: me
  ports:	
  - port: 3000	
    targetPort: 3000	
    protocol: TCP	
  type: LoadBalancer 