apiVersion: apps/v1
kind: Deployment
metadata:
  name: me
spec:
  selector:
    matchLabels:
      run: me
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: me
    spec:
      containers:
      - name: me
        image: jeg910716/me
        ports:
        - containerPort: 80
---	
apiVersion: v1	
kind: Service	
metadata:	
  name: me
  labels:	
    run: me
spec:	
  selector:	
    run: me
  ports:	
  - port: 3000	
    targetPort: 3000	
    protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: me
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /me
        backend:
          serviceName: me
          servicePort: 3000
  # tls:
  # - hosts:
  #   - localhost
  #   secretName: tls-me-secret
  